services:
  api:
    image: api
    build:
      context: ./api
      args:
          CLIENT_URL: ${CLIENT_URL}
    container_name: api
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"

  client:
    image: client
    build:
      context: ./client
      args:
          API_URL: ${API_URL}
    container_name: client
    restart: unless-stopped
    ports:
      - "127.0.0.1:5173:80"
