- name: Set user & group
  block:
      - name: Create '{{ cassandra_group }}' group
        shell: sudo groupadd -f '{{ cassandra_group }}'

      - name: Create '{{ cassandra_user }}' user with temporary password
        user: 
          name: "{{ cassandra_user }}"
          password: "{{ '1234' | password_hash('sha512') }}"
          groups: "{{ cassandra_group }}"
          home: "{{ cassandra_dir }}"
          shell: "/bin/bash"
          register: user

      - name: Force '{{ cassandra_user }}' to change password
        shell: chage -d 0 '{{ cassandra_user }}'
        when: user.changed

      - name: Revoke others rights from '{{ cassandra_dir }}'
        shell: chmod 760 '{{ cassandra_dir }}'

  rescue:
    - import_tasks: ./helpers/on-error.yaml
