- name: Adjust access
  block:
      - name: Include credentials file
        include_vars:
          file: credentials.yaml
          
      - name: Set postgres password
        shell: sudo -u postgres psql template1 -c "ALTER USER postgres with encrypted password '{{ postgres_password }}'"

      - name: Set postgres authentication method
        lineinfile: 
          path: /etc/postgresql/{{ version }}/main/pg_hba.conf
          regexp: 'local[ \t]+all[ \t]+postgres[ \t]+peer' 
          line: 'local all postgres md5'
          backrefs: yes
          firstmatch: yes

      - name: Set user external TCP/IP connection (IPv4)
        blockinfile: 
          path: /etc/postgresql/{{ version }}/main/pg_hba.conf
          marker: "# {mark} IPv4 CONNECTIONS BLOCK"
          block: |
              host {{ database }} {{ user }} 0.0.0.0/0 md5
              host {{ shadow_database }} {{ user }} 0.0.0.0/0 md5

      - name: Set user external TCP/IP connection (IPv6)
        blockinfile: 
          path: /etc/postgresql/{{ version }}/main/pg_hba.conf
          marker: "# {mark} IPv6 CONNECTIONS BLOCK"
          block: |
              host {{ database }} {{ user }} ::/0 md5
              host {{ shadow_database }} {{ user }} ::/0 md5

      - name: Restart postgres
        shell: sudo /etc/init.d/postgresql restart
