- name: Create user
  block:
      - name: Include credentials file
        include_vars:
          file: credentials.yaml

      - name: Add user
        shell: sudo -u postgres psql -c "CREATE USER {{ user }} WITH PASSWORD '{{ user_password }}'";

      - name: Change database ownership
        shell: sudo -u postgres psql -c "ALTER DATABASE {{ database }} OWNER TO {{ user }};"

      - name: Change shadow database ownership
        shell: sudo -u postgres psql -c "ALTER DATABASE {{ shadow_database }} OWNER TO {{ user }};"
