- name: Create user
  block:
      - name: Include credentials file
        include_vars:
          file: credentials.yaml

      - name: Add user
        shell: sudo -u postgres psql -c "CREATE USER {{ user }} WITH PASSWORD '{{ user_password }}'";

      - name: Grant privileges
        shell: sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE {{ database }} TO {{ user }};"

      - name: Grant database ownership
        shell: sudo -u postgres psql -c "ALTER DATABASE {{ database }} OWNER TO {{ user }};"
