- name: Create dbs
  block:
      - name: Create primary db (if not exists)
        shell: sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = '{{ database }}'" | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE {{ database }}"

      - name: Create shadow db (if not exists)
        shell: sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = '{{ shadow_database }}'" | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE {{ shadow_database }}"
